In [1]:
import pandas as pd
import numpy as np

# ***Task 01***

# **Create a Pandas Series of 6 countries and their populations.**

In [3]:
countries_series = pd.Series(
    {
    "Pakistan" : 223453424 ,
    "India" : 345342424444 ,
    "China" : 313424256344 ,
    "Iran" : 3156344 ,
    "Japan" : 32314245 ,
    "England" : 32431524    }
)

countries_series

Pakistan       223453424
India       345342424444
China       313424256344
Iran             3156344
Japan           32314245
England         32431524
dtype: int64

# ***Task 02***

# **Create a DataFrame for 5 employees with Name, Department, Salary, and Experience.**

In [15]:
employess_stats = pd.DataFrame([
    { "Name" : "Owais Nadeem" ,
    "Dept": "BSCS" ,
    "Salary": 80000 ,
   "Experience": 2
} , {
    "Name" : "Hamza Arshad" ,
    "Dept": "BSAI" ,
    "Salary": 120000 ,
   "Experience": 3
} , {
    "Name" : "Zeeshan Ashraf" ,
    "Dept": "Masters" ,
    "Salary": 280000 ,
   "Experience": 6
} , {
    "Name" : "Kanza Yusuf" ,
    "Dept": "BSCS" ,
    "Salary": 180000 ,
   "Experience": 4
} ,{
    "Name" : "Hassan Yousuf" ,
    "Dept": "BSCS" ,
    "Salary": 20000 ,
   "Experience": 1 }
] )

employess_stats

             Name     Dept  Salary  Experience
0    Owais Nadeem     BSCS   80000           2
1    Hamza Arshad     BSAI  120000           3
2  Zeeshan Ashraf  Masters  280000           6
3     Kanza Yusuf     BSCS  180000           4
4   Hassan Yousuf     BSCS   20000           1

# ***Task 03***

# **Add a column 'Bonus' = 15% of salary.**

In [16]:
# Add a column Bonus = 15% of salary.

df = employess_stats

df["Bonus"] = df["Salary"] * 0.15
df

             Name     Dept  Salary  Experience    Bonus
0    Owais Nadeem     BSCS   80000           2  12000.0
1    Hamza Arshad     BSAI  120000           3  18000.0
2  Zeeshan Ashraf  Masters  280000           6  42000.0
3     Kanza Yusuf     BSCS  180000           4  27000.0
4   Hassan Yousuf     BSCS   20000           1   3000.0

# ***Task 03***

# **Filter employees with more than 3 years of experience.**

In [21]:
# Filter employees with more than 3 years of experience.

experienced_employees = df.copy()

experienced_employees = (df[df["Experience"] > 3])

experienced_employees

             Name     Dept  Salary  Experience    Bonus
2  Zeeshan Ashraf  Masters  280000           6  42000.0
3     Kanza Yusuf     BSCS  180000           4  27000.0

# ***Task 04***

# **Sort employees based on Salary in descending order.**

In [22]:
# Sort employees based on Salary in descending order.

employees_sorting = df.copy()

sorted_df = employees_sorting.sort_values(by="Salary" , ascending = False)

sorted_df

             Name     Dept  Salary  Experience    Bonus
2  Zeeshan Ashraf  Masters  280000           6  42000.0
3     Kanza Yusuf     BSCS  180000           4  27000.0
1    Hamza Arshad     BSAI  120000           3  18000.0
0    Owais Nadeem     BSCS   80000           2  12000.0
4   Hassan Yousuf     BSCS   20000           1   3000.0